### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by etagwerker** [manuelmeurer/railsbump#26] opened 2020-01-20 14:58 UTC
Hi there, 

First of all, thanks for writing and maintaining this project! We've been using it at https://www.fastruby.io for a while. 

Unfortunately, it seems that both ready4rails.net and https://railsbump.org are not working. 

1. ready4rails.net now seems to redirect to some spammy website
2. https://railsbump.org responds with a rails 404 page

My company and I would love to collaborate on this project and help out if possible. Is there anything we can do to help? 

Please let me know.

Thanks!

**Comment by manuelmeurer** [comment] 2020-01-20 20:36
Hi @etagwerker,

I took over ready4rails.net from @Florent2 in December and I my plan is to rebuild and automate it, i.e. check automatically which versions of a specific gem are compatible with which major versions of Rails.
I actually planned to have something working by now already, which is why I took down the current site. But, as usual, life got in the way. :)

I'm interested to hear more about how you would like to use the service. My idea was that it should be able to upload (or copy & paste) from an app a Gemfile that runs on Rails 5 for example, and RailsBump tells you which gems are compatible with Rails 6 and, for those that are not compatible yet, links to issues where compatibility is being worked on. You should also be able to 'watch' Gems and get an email notification when a version is released that is compatible.

P.S.: ready4rails.net should not redirect to some spammy website. I just tried it (with and without www) and it redirects to railsbump.org. Does it still redirect somewhere else for you?

**Comment by etagwerker** [comment] 2020-01-21 01:27
@manuelmeurer Hi and thanks for the quick response! 

> check automatically which versions of a specific gem are compatible with which major versions of Rails.

This is a great idea and I'd really like to see something like that. I'm one of the maintainers of https://rubygems.org/gems/next_rails which has a basic way to check for incompatibilities.

> I'm interested to hear more about how you would like to use the service.

We run a [productized service to upgrade Rails applications](https://www.fastruby.io). Our clients hire us to get them from one version of Rails to a more recent one. One of our resources is "The Complete Guide to Upgrade Rails" (from Rails 2.3 to 6.0) and it mentions http://ready4rails.net as a tool to be used in your upgrading efforts. 

> P.S.: ready4rails.net should not redirect to some spammy website. I just tried it (with and without www) and it redirects to railsbump.org. Does it still redirect somewhere else for you?

My bad, I was using `http://ready4rails4.net` which does redirect to a spammy website. `ready4rails.net` works well.

**Comment by manuelmeurer** [comment] 2020-01-25 22:01
Cool, thanks for the info!
AFAICS, the `bundle_report compatibility` command of `next_rails` basically already does the heavy lifting of checking for Rails compatibility, so that helps a lot!
I hope I will have time to work on RailsBump in the upcoming weeks...

**Comment by manuelmeurer** [comment] 2020-01-30 09:34
Hi @etagwerker, I found some time in the last days to work on RailsBump. At least it's not the Rails error page on https://railsbump.org/ anymore. 😉 
I also came up with a way to test the compatibility of lots of gems with all major Rails versions, quickly and for free, by using Travis CI. 😄 I'm 90% sure it will work and I hope I can get it done within the next week. Looking forward to hear what you think about it!

**Comment by etagwerker** [comment] 2020-02-05 15:11
@manuelmeurer That's great. I have some time to help with this, if you need some help with it. It's in our best interest to make sure this project is up to date, because it's a great resource for the consulting work we do at @fastruby. So let me know if me or my team can help. 😃

**Comment by manuelmeurer** [comment] 2020-02-07 08:58
Thanks! I think it's best if I get the basic version up and running first, then we can talk about new features and improvements and work on it together.

**Comment by manuelmeurer** [comment] 2020-02-15 21:06
@etagwerker Ok, so I think it should work well enough for you to try it out now. :)
This is how the end result of checking a gem looks like right now:
https://railsbump.org/gems/services
Not too pretty I admit...

The way it works is that when you [add a gem](https://railsbump.org/gems/new)) it checks Rubygems.org for all versions of the gem and all the different dependencies each version has. For each unique set of dependencies and each Rails version we're interested in (4.2, 5.2 and 6.0), the app creates a branch in a [separate repo](https://github.com/manuelmeurer/railsbump-checker) that contains a Gemfile with those dependencies and a Travis config file with a webhook URL.
Here's an example: https://github.com/manuelmeurer/railsbump-checker/tree/33
Travis then installs the dependencies and, if it works, runs a Rake task that does nothing. Afterwards it reports to the webhook whether the build succeeded (i.e. the dependencies are compatible) or that it didn't succeed (i.e. there was an error installing the dependencies -> they are not compatible with that version of Rails).

Try adding a gem, then you should see the builds pop up here: https://travis-ci.com/manuelmeurer/railsbump-checker/builds

I'm sure there are lots of things to improve, but this was how I imagined it to work.
What do you think?

**Comment by etagwerker** [comment] 2020-02-16 05:08
@manuelmeurer That's really interesting. I just tested a couple of gems and I think that I brought the site down. Sorry about that! 😸 

I submitted a couple of tests:

- `hestia`
- `attr_encrypted`

Any chance we can get a view where we can find compatibilities/incompatibilities per Rails version? Something like https://railsbump.org/rails/4-2/gems which will list all gems and show the compatible/incompatible attribute.

Thanks!

**Comment by vzelenko** [comment] 2020-02-17 12:52
@manuelmeurer - do you mind throwing a dummy required config for this project or Dockerizing it?

**Comment by manuelmeurer** [comment] 2020-02-17 19:30
Oh jeez, lots of `ActiveRecord::ConnectionTimeoutError` are happening, since the app uses the Heroku Postgres "Hobby Dev" plan... I'll move the DB to a Amazon RDS database I already use for other projects.

**Comment by manuelmeurer** [comment] 2020-02-17 20:06
Hmm, using a Amazon RDS db won't work, I would have to remove all restrictions regarding from which IP it can be accessed, can't do that unfortunately.
So we'll have to work with the 20 connection limit of the Heroku Postgres db.
I increased the Active Record connection pool and limited the number of Sucker Punch workers to 1, let's see if that helps...

**Comment by manuelmeurer** [comment] 2020-02-17 20:10
> Any chance we can get a view where we can find compatibilities/incompatibilities per Rails version? Something like [railsbump.org/rails/4-2/gems](https://railsbump.org/rails/4-2/gems) which will list all gems and show the compatible/incompatible attribute.

Probably the main view should be a big table of all available gems (with some kind of endless scrolling) and their compatibility.

**Comment by manuelmeurer** [comment] 2020-02-17 20:23
> @manuelmeurer - do you mind throwing a dummy required config for this project or Dockerizing it?

I've made all ENV vars optional now. The only one that's really needed is `FONTAWESOME_PRO_TOKEN` to install the Fontawesome Pro icons...
To run the app without them, simply remote the line from `.npmrc`.
Or is there any way to tell NPM to ignore non-existing ENV vars?

**Comment by vzelenko** [comment] 2020-02-17 20:48
NICE!  Looks stable for now.  My Gemfile keeps resulting in error: `Validation failed: Name is reserved`- and I can't find the source.  Attaching Gemfile...


[Gemfile.txt](https://github.com/manuelmeurer/railsbump/files/4216122/Gemfile.txt)

**Comment by jasnow** [comment] 2020-02-17 20:59
@vzelenko - what command are you running when you get the above error msg?

**Comment by jasnow** [comment] 2020-02-17 21:08
Gemfile is ruby code so you can add **puts** lines in your Gemfile file to do a binary divide-and-conquer when you run "bundle".

**Comment by vzelenko** [comment] 2020-02-17 21:10
@jasnow - no,  the error hits on this page:  https://railsbump.org/gemfiles/new

**Comment by jasnow** [comment] 2020-02-17 21:30
I can reproduce the problem. Do not run Ruby 2.2.3 on my projects so installing it. Failed on my old Mac OS - Found "--disable-dtrace" to hopefully work around that.

**Comment by jasnow** [comment] 2020-02-17 21:31
Why are you using ruby 2.2.3?

**Comment by jasnow** [comment] 2020-02-17 22:02
Got Ruby 2.3.1 (my oldest install ruby to run bundle). Then found:
```
$HOME/.rvm/gems/ruby-2.3.1@ruby2.3-rails4.2-r4r/gems/activerecord-4.2.4/lib/active_record/locale/en.yml:        record_invalid: "Validation failed: %{errors}"
$HOME/.rvm/gems/ruby-2.3.1@ruby2.3-rails4.2-r4r/gems/activemodel-4.2.4/lib/active_model/locale/en.yml:      exclusion: "is reserved"
$HOME/.rvm/gems/ruby-2.3.1@ruby2.3-rails4.2-r4r/gems/rails-4.2.4/guides/source/active_record_validations.md:    message: "%{value} is reserved." }
```

**Comment by manuelmeurer** [comment] 2020-02-18 08:47
@vzelenko Oops sorry, this should be fixed. It's not allowed to create the gem "rails", since it's nonsensical to check the compatibility of rails with rails. :)
So that name is reserved, and of course when all the gems of a Gemfile are parsed, it should be ignored.

**Comment by vzelenko** [comment] 2020-02-18 12:36
@manuelmeurer - Thanks for addressing this quickly.  The Gemfile is now being processed.  Actually, it looks STUCK after some gems got successfully checked out,  but this is no longer a place to rant on about it.  I'll wait for a bit longer and start a new issue if the process does not complete.

GREAT WORK!!!

**Comment by manuelmeurer** [comment] 2020-05-15 12:53
I'm closing this for now.
Please watch this repo for releases to be notified when the first usable version is up and running (hopefully next week). I'll add my ideas for new features and improvements as issues today.

**Closed by manuelmeurer** 2020-05-15 12:53 UTC
